### PR TITLE
Support for ORY hydra v2.1.2

### PR DESCRIPTION
**Pull request by kubek2k**

### CODE REVIEW

**Comment by lykahb** [comment]
Thank you! Do you know why the module names changed from OryHydra to ORYHydra? I ran into that when doing an upgrade before. This must come either from the OpenAPI files or the openapi generator itself.

**Comment by kubek2k** [comment]
@lykahb Hi! I think it is caused by my invocation of `openapi-generator`:
```
openapi-generator-cli generate -i openapi.yaml -g haskell-http-client --additional-properties=cabalPackage=ory-hydra-client --additional-properties=baseModule=ORYHydra --additional-properties=requestType=ORYHydraRequest --additional-properties=strictFields=false --additional-properties=requestType=ORYHydraRequest --additional-properties=configType=ORYHydraConfig --type-mappings "AnyType=A.Value" --additional-properties=allowNonUniqueOperationIds=true
```

I did this to adhere to the filenames, because otherwise I wasn't able to compile the thing (the file named eg. `ORYHydra.Core`  containing the module named `OryHydra.Core`. I think it has something to do with the filesystem that I am dealing with on MacOS and git. When I think of it now - maybe it makes sense to keep the `OryHydra` naming scheme (ie. change the invocation ☝️ ), to cause less headaches? (as of now we were encountering issues on Linux machines)

**Comment by lykahb** [comment]
Thank you for the PR and sharing the details for the invocation. I realized that you figured out the call yourself instead of using the instructions under the `generator-settings` branch. So, I've decided to reorganize the directory structure to put the generated client under a directory and the instructions to generate a client on the top-level. This solves the problem with discovering the branch `generator-settings` and having the generated README for the repository page.

I also added several properties from your invocation into the config for the generator. The last time I did an update, I had to solve the type mappings problem in the test suite manually. 

The 2.1.2 is now in the repository and is uploaded to hackage.

**Comment by kubek2k** [comment]
@lykahb thanks a lot - I had no idea that such branch is there 🙌 . Thanks for updating the client. As a side note - I created another branch with similar idea (`generate.sh` script with proper invocation) - so it has to be good :D .

**Pull request closed without merging**
